name: Build and Push to Nexus

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          server-id: nexus
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD

      - name: Build Project
        run: mvn clean package -DskipTests

      - name: Deploy to Nexus
        run: mvn deploy -DskipTests
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
